apiVersion: v1
kind: Service
metadata:
  name: my-docker-app-service
spec:
  selector:
    app: my-docker-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
     